(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 724,
	height: 543,
	fps: 24,
	color: "#000033",
	manifest: []
};



// symbols:



(lib.mc4 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9C63A8").s().p("AxjosMAjHAAAMgjHARZg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.4,-55.7,224.9,111.6);


(lib.mc3 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F9F353").s().p("AxjosMAjHAAAIAARZg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.4,-55.7,224.9,111.6);


(lib.mc2 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF68A2").s().p("AxiItIAAxZMAjFARZg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.3,-55.7,224.7,111.5);


(lib.mc1 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#16B6C6").s().p("AxiItMAjFgRZIAARZg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.3,-55.7,224.7,111.5);


(lib.刷新 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.298)").s().p("AAeBcQgHgDAAgFQAmAJgBggIAAgdIABAAIACAEIAIAJIACACIAAAMIAAAFIAAAHQABAZgXAAQgJAAgMgEgACeBSIAAAAQAKgCABgJIAAhgIAMAAQAKAAAAgMIAAgCIADAAQAKABAAAMQAAALgKAAIgMAAIAABgQgBAKgMACQgLgBAAgKgAiFBQIAAAAQAJgCAAgIIAAgHIAAAAQADAIAOgCQAQgBABgNIAAgkQAAAJAJACQABACADACIAAAMQgLgBgCALQABAIAKAEIABABQgDAKgNABQgOABgDgIIAAAHQAAAKgLAAQgLAAAAgKgABhBWQgCgDgBgEQAFgBAFgFQAXgYABg1IAAgVIAIAAIAABIQgGAXgNAOQgGAGgGAAQgEAAgEgEgAg3BVQgLgCgCgIQAqAMgCgfIAAiWIAAgBIABAAQALAAABALIAACFIAAAGIAAALQABAXgVAAQgIAAgMgEgAilBIIAAAAQAIgCABgIIAAhAIACgCIAABEQAAAJAJABIABACQgDAFgIABQgKgBAAgJgAjEBQQgIgDABgHQAHgBADgHQAEgKACgMIAAAQQAAAIAJACIAAAAIgCAGQgDAJgJAAIgEgBgAAIBMIADAAIAAABIgDgBgAATA4IAKgSIAAAPQAAADgFAAIgFAAgAhFAkQAHgCACgFIAAAOIAAADQgIgCgBgIgAh8gFIADAAIAAAsQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAgAAbATIgBgBIgEgBQgBgDgEgCQgEgCgEAAIAAgCIAUAAIAAALgABNASIgCgCQgIgGgHAGIAAgIIAfAAIAEgBIgCALgABfgMIgEgBIgBAAQgCgFgGgBIgWAAIAAgDIAdAAQAEAAADgCIAAAMgAhbgRIABAAIAAACIgBgCgAAKgTIgBgDIAUAAIAAADgAizgrIAZAAIAAAJIgPAAQgGAAgFACIABgLgAhcggIgOAAQgFgCgHAAIgGAAIAAgJIATAAQALABAEgHIAAARIgBAAIgBAAgABbgtQgCgGgHAAIgBAAIABgFIAEgNIAFAAQADAAACgCIAAAXIgBACIAAACIgEgBgAArgzIAAgCIgEgQIAOAAIgFASgACAg3IAAgOQABgDADgBQAYAAAWgFQAIgBABgKIAAgCIAFAAQAIABAAALQgBAKgIACQgWAFgYAAQgDABgBADIAAADgAi0hIIAAgIQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAgBIA6AAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAgAhahfIACAAIgBACIgBgCg");
	this.shape.setTransform(-2,1.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.988)").s().p("AAgBfIgCgBIAAAAQgGgDgBgFQgBgEACgFQgGAEgFgBQgDgBgDgCIgCgEIAAgGIADgFQAKgMAHgQQACgFAEAAQADgBAFACQADACACADQADAEgCAHQgJARgHAKQADgBAFABIAEABQAKACAAgEIAAgPIAAgSIAAgCIAAgKIAAgGIggAAQgJgBgBgLQABgJAJAAIAMAAIAUAAIAAgEIAAgGIggAAQgJAAgBgLQABgLAJgBIARAAIgGgSIgBgFIgFAAQgJgBgBgLQACgLAJAAIAcAAIgBgDQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQgCgJALgDQAKgBAEAHIABADIABAIIAHAAIABAAIARAAQAGAAACAGIACAFQAAAMgIAAIgFAAIgEANIgCALIAJAAIACAAQAGABADAFIABAHQgCAKgKAAIgdAAIAAAKIAJAAIAWAAQAGAAACAEIABAFQgBALgIAAIgfAAIAAA1QABAZgXAAQgIAAgLgDgAA4goIACAHIAHAAIAFAAIAEgSIACgGIgYAAIAEARgACnBeQgJgBAAgJIAAgTIAAhIIAAgGIgRAAIAAAUQgBA3gXAYQgHAGgGAAQgDgBgEgDIgCgGIAAgEQABgFADgFIABgBIgBAAQgCAAgCgCIgCgCIgIgIIgDgEIAAgBQgHgIAGgHIABgBQAHgGAHAGIACADIABABIALAMIABgDIADgKIACgMIABgUIAAAAIAAgKIAAgUIAAgEIAAgXIAAgLIAAgIQADgOAWACQANAAAUgEIARgCQAFAAACAGIABAGQgBAKgIACQgWAFgYAAQgDABgBADIAAATIAJAAIANAAIAfAAQAHAAACAGIABAHQAAALgKAAIgMAAIAABgQgBAKgMACIgCgBgAh8BcQgJgBAAgJIAAhGIAAgGIgHAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAIAABCQgBAJgLABIgBAAQgJgCAAgIIAAgPIAAg5QgBgLAIgEQAEgCAHAAIAOAAIAAgJIAAgGIghAAQgBBGgNAiQgEAKgKgCIgCAAQgKgEAEgLQALgiABg1IAAg2QAAgTAPAAIBTAAQAKAAAEAGQACAEAAAGIAAAfQABARgRgBIgTAAIAAAPIAJAAIAGAAQAHgBAEACQAEACACADQACAEAAAFIAABDQgBAOgQABIgIAAIAAAAQgHgCgCgFIAAAHQAAAKgLAAIgCAAgAhvA/QAAgDAFAAIAEAAQAAAAABgBQAAAAABAAQAAAAAAgBQAAAAAAgBIAAgtIAAgEIgCgCIgJAAgAinhEIAAAOIAIAAIA6AAQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIAAgIIAAgEIgCgCIhAAAQAAAAgBAAQAAAAgBABQAAAAAAAAQAAABAAAAgAg3BXIgDgBQgJgDgBgJQACgKAKAAIABAAIADACQANAEABgGIAAgCIAAgPIAAhzIAAgNQAAgLALgBQAIAAADAGIABAFIAACWQABAWgVAAQgIAAgMgDgAg7AwQgKgCAAgJIAAghIAAgDIAAgBIAAgOIAAgRIAAglIABgGIACgCQACgEAGAAQAIAAADAGIABAFIAABqQgBAKgKABIgCAAg");
	this.shape_1.setTransform(-4.2,-0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(87,18,11,0.988)").s().p("AAjBgIgGgCQgDgCgCgDIgBAAQAqAMgBgiIAAg1IAfAAQAIAAABgLIgBgEIAAAAIAEABIABAAIgBATIgEABIgeAAIAAAIIgBABQgGAHAHAIIAAAdQAAAZgWAAQgHAAgJgCgACeBYIACAAQAMgBABgKIAAhgIAMAAQAKAAAAgMIgBgGQAJAAABAKIAAACQgBAMgJAAIgNAAIAABgQAAAJgLACIgBAAQgJAAgCgGgAiDBYIgCgCIACAAQALgBAAgJIAAgIQACAGAHABIAAAHQgBAIgIACIgDAAQgGAAgCgEgABhBYIgCgCQAHAAAGgHQAXgYABg3IAAgTIARAAIAAAGIgIAAIAAATQgBA3gXAYQgFAFgFABIgCABQgEAAgEgEgAg3BXQgHgCgDgDIgCgCIADABQAqAMgCgfIAAiWIgBgFQAJABABAJIAAABIAACWQABAWgVAAQgJAAgLgDgAilBOIAAAAIABAAQALgBABgJIAAhCQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAHAAIAAAGIgBACIAABCQgBAIgJACIgCAAQgIgBgCgFgAjFBSQgFgCgBgEQAKABAEgJQANgiABhHIAhAAIAAAGIgZAAIAAAMQgIAEABAMIAAA3QgDANgDAJQgDAHgHABIgCAAIgFAAgAhvBLIAIAAQAQgBABgNIAAhDQAAgFgCgEQAJACABAIIAAACIAAADIAAAfIAAAkQgBANgPABIgEABQgKAAgDgHgAAHBMIgCgCQAFAAAFgDQgCAFABAEQgEgBgDgDgAAcBDQgFgBgDABQAHgKAJgSQACgGgDgEIADABIACABIACACIAAARIgKASIgEgBgABaA9IABAAIAAAAgAh4AAIAJAAIACACIAAADIgCAAIAAAxIgEgBQgFAAAAAEgAhBAuQgCgCgBgCIACAAQAKgBABgLIAAhqIgBgEQAHAAACAGIAABzQgCAFgHACIgCAAQgEgBgDgBgABbAfIAFADIAGAHIgBACIgKgMgAAWAUIgDAAQgHAAgCgGIAgAAIAAAGgABAgHIAAgJIAdAAQAKAAACgLIgBgGIADABIABAAIAAAUQgCACgEAAIgdAAIAAADgAAWgKIgDAAQgHAAgCgGIAgAAIAAAGgAh4gWIAAgPIATAAQARACgBgSIAAgeQAAgGgCgEQAIACACAIIABACIgCAHIAAAlQgDAHgMgBIgSAAIAAAJgABUgnIACgLIAEgNIAFAAQAIAAAAgMIgBgGIAAAAQAEABACADIAAAIIAAAKQgCACgDAAIgFAAIgDANIgBAFgAAxgnIgCgIIgEgQIAYAAIgCAGIgNAAIADAQIABACgACEgrIAAgUQABgDADgBQAYAAAWgFQAIgBABgKIgBgHIABAAQAIABABAKIAAACQgBAKgIABQgWAFgYAAQgDABgBADIAAAOgAAPg/IAFAAIACAGQgFgBgCgFgAiwg8IAAgOQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBIBAAAIACADIAAADIg5AAQgBABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABIAAAIgABEhXIgBgIIgBgCQAHABACAHIABACg");
	this.shape_2.setTransform(-3.3,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FE7D55").s().p("AmlC4QgMAAgIgFQgDgGAAgJIAAk/QAAgcAcAAINHAAQAMAAAHAFQADAGAAAJIAAE/QAAAcgcAAg");
	this.shape_3.setTransform(-0.6,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#80180D").s().p("Am9CjIAAk/QAAgdAcAAINGAAQATAAAGAOQgHgGgLAAItIAAQgcAAAAAcIAAE/QAAAJADAHQgJgIABgPg");
	this.shape_4.setTransform(-1,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F44940").s().p("AjrD1QglAAAAglIAAmgQAAgkAlAAIH8AAIipHpg");
	this.shape_5.setTransform(-24.6,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(206,46,20,0.996)").s().p("AlFD1ICpnpIG+AAQAkAAAAAkIAAGgQAAAlgkAAg");
	this.shape_6.setTransform(18.4,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#80180D").s().p("AnfD1QglAAABgkIAAmgQgBglAlAAIPAAAQAjAAABAlIAAGgQgBAkgjAAg");
	this.shape_7.setTransform(0.3,0.5);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-52,-25,104,50.1);


// stage content:
(lib.donghua2 = function() {
	this.initialize();

	// 图层 1
	this.updateBtn = new lib.刷新();
	this.updateBtn.setTransform(638.6,495.8,1,1,0,0,0,0,10.1);

	this.mc4 = new lib.mc4();
	this.mc4.setTransform(474.2,326.6);

	this.mc3 = new lib.mc3();
	this.mc3.setTransform(249.1,326.6);

	this.mc2 = new lib.mc2();
	this.mc2.setTransform(473.6,215.1);

	this.mc1 = new lib.mc1();
	this.mc1.setTransform(249.2,215);

	this.addChild(this.mc1,this.mc2,this.mc3,this.mc4,this.updateBtn);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(498.6,430.8,554,351.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;